# Generated by Django 3.0.5 on 2020-06-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=122)),
                ('StudentFirstName', models.CharField(max_length=122)),
                ('StudentMidleName', models.CharField(max_length=122)),
                ('StudentLastName', models.CharField(max_length=122)),
                ('StudentMobile', models.CharField(max_length=13)),
                ('ParentFirstName', models.CharField(max_length=122)),
                ('ParentMidleName', models.CharField(max_length=122)),
                ('ParentLastName', models.CharField(max_length=122)),
                ('ParentMobile', models.CharField(max_length=13)),
                ('Adress', models.TextField()),
                ('Selection', models.CharField(max_length=50)),
                ('Question', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
